name: "Build for Multiple Platforms & Create Release"
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: ["osx-arm64", "linux-64", "win-64"]
      fail-fast: false

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Run Pixi-Pack
        uses: wytamma/pixi-pack-action@v2
        with:
          platform: ${{ matrix.platform }}
          name: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.platform }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.sh, *.ps1"
