name: "Build for Multiple Platforms & Create Release"
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: ["osx-arm64", "linux-64", "win-64"]
      fail-fast: true

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Run Pixi-Pack
        uses: wytamma/pixi-pack-action@c830115cf4bb114b3b32288dfd95ac5dea74ab80
        with:
          platform: ${{ matrix.platform }}
          entrypoint: ${{ matrix.platform == 'linux-64' && 'python' || '' }} # create once for unix

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ github.event.repository.name }}-*.sh, ${{ github.event.repository.name }}-*.ps1, install.sh"
  create-install-script-and-release:
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - name: Create install script
        uses: wytamma/pixi-pack-install-script@37fc6c18e4ca0001d3e844a65304e4589d810acb
        with:
          entrypoint: "python"

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: "install.sh"
